### ISSUE TITLE
No icons in Lisp mode

### ISSUE THREAD

**Issue by margaretjoanmiller** [LuigiPiucco/nerd-icons-corfu#12]
Is there a way to enable icons in Lisp mode? Or generically is there a way to configure support for more modes?

**Comment by LuigiPiucco** [comment]
The icons are enabled for Corfu as a whole, so if corfu-mode is on at those points, so are the icons (after you add the margin formatter like in the README, that is). However, it may be the case that your completion-at-point functions (the ones that generate the candidate list) don't annotate their tables with the candidate type, or add something not recognized by the default mappings. To troubleshoot this, first I need the value of `completion-at-point-functions` from inside a buffer where this is an issue. I'll check if any of the listed CAPFs don't return `:company-kind` properties. If they don't, there's not much that can be done here, as the CAPFs themselves should implement that (possibly via an extension package).

EDIT: By the way, by "Lisp mode" you mean Common Lisp, correct? Or are you talking about Emacs Lisp (Elisp)?

**Comment by LuigiPiucco** [comment]
I'll close this due to inactivity.
