### ISSUE TITLE
the icon is not fully displayed

### ISSUE THREAD

**Issue by stardiviner** [LuigiPiucco/nerd-icons-corfu#7]
As bellowing screenshot displayed:

<img width="651" alt="Screenshot 2023-10-14 at 13 09 29" src="https://github.com/LuigiPiucco/nerd-icons-corfu/assets/378699/546c5e77-dda3-4520-a4d8-375bfafcb716">

Does anyone know how to fix this?

**Comment by LuigiPiucco** [comment]
I'll look into it. I think this may be due to the size of those particular icons being different. I've observed similar behavior every once in a while, but always with specific icons. Do some of them look OK and some not?

**Comment by stardiviner** [comment]
After updated package to latest version. I found this [commit](https://github.com/LuigiPiucco/nerd-icons-corfu/pull/6/files) seems fixed the problem. (It seems changed the returned `str` which added space)

<img width="554" alt="image" src="https://github.com/LuigiPiucco/nerd-icons-corfu/assets/378699/c7245284-a4b9-461a-9df0-c1d344133239">

**Comment by stardiviner** [comment]
Sorry for re-opening this issue, and maybe not focus on original issue.

<img width="458" alt="image" src="https://github.com/LuigiPiucco/nerd-icons-corfu/assets/378699/49681e69-2ff3-43f3-af3d-5b57803ead85">

The corfu candidates seems offset not align same with the user input text vertically. (Maybe this is also caused by the extra space? Might need to re-calculate the popup frame offset?)

**Comment by seagle0128** [comment]
@stardiviner My patch should address this issue.

**Comment by stardiviner** [comment]
@seagle0128 thanks for patching. confirmed the icons displayed fully now.
Now it caused the corfu candidates displayed truncated with the last character.
In bellowing screenshot, the last character `s` is truncated.

![Screenshot 2023-10-19 at 10 37 52](https://github.com/LuigiPiucco/nerd-icons-corfu/assets/378699/a35effac-ee5a-4aae-83d0-4875a14798ef)

**Comment by seagle0128** [comment]
@stardiviner The patch #8 hasn't been merged, which fixes all issues including aligning and  truncated.

@LuigiPiucco Please merge ASAP.

**Comment by stardiviner** [comment]
@seagle0128 Tried the latest commit, confirmed fixed. Thanks :)

**Comment by seagle0128** [comment]
welcome
